#!/bin/bash

if [[ "$OSTYPE" == "msys" ]]; then
    cmake -G "MinGW Makefiles" -S . -B build
    cmake --build build
    echo "Enter your path to include dir (C:/mingw): "
    read include_path  
    cmake --install build --prefix ${include_path}
else
    mkdir build
    cd build
    cmake ../
    cmake --build .
    sudo cmake --install .
fi