name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build CMAKE
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing dependencies
      run: |
        curl -k -L https://sourceforge.net/projects/arma/files/armadillo-12.0.1.tar.xz | tar -xvJ && \
                cd armadillo* && \
                cmake . && \
                make && \
                sudo make install && \
                cd ..

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      